name: flutter_sidenav
description:  Simple side-nav widget for Flutter
version: 1.0.0-non-nullsafety
homepage: https://github.com/kfiross/flutter_sidenav

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
